package helper

const PathResponseCustomerTransaction = `
            customer_transactions.created_by_id,
            customer_transactions.created_at,
            customer_transactions.updated_by_id,
            customer_transactions.updated_at,
            customer_transactions.deleted_by_id,
            customer_transactions.deleted_at,
            customer_transactions.period,
            customer_transactions.customer_id,
            SUM(customer_transactions.debit) AS debit,
            SUM(customer_transactions.credit) AS credit,
            SUM(customer_transactions.opening_balance) AS opening_balance,
            COALESCE(SUM(customer_transactions.opening_balance), 0)
            + COALESCE(SUM(customer_transactions.debit), 0)
            - COALESCE(SUM(customer_transactions.credit), 0) AS closing_balance,
            Customer.id AS Customer__id,
            Customer.created_at AS Customer__created_at,
            Customer.updated_at AS Customer__updated_at,
            Customer.deleted_at AS Customer__deleted_at,
            Customer.created_by_id AS Customer__created_by_id,
            Customer.updated_by_id AS Customer__updated_by_id,
            Customer.deleted_by_id AS Customer__deleted_by_id,
            Customer.name AS Customer__name,
            Customer.address AS Customer__address,
            Customer.npwp AS Customer__npwp,
            Customer.latitude AS Customer__latitude,
            Customer.longitude AS Customer__longitude,
            Customer.ktp AS Customer__ktp,
            Customer.image_npwp AS Customer__image_npwp,
            Customer.image_ktp AS Customer__image_ktp,
            Customer.approved_by AS Customer__approved_by,
            Customer.approved_at AS Customer__approved_at,
            Customer.status AS Customer__status,
            Unit.id AS Unit__id,
            Unit.nama_unit AS Unit__nama_unit,
            Unit.address AS Unit__address,
            Unit.image AS Unit__image,
            Unit.approved_by AS Unit__approved_by,
            Unit.approved_at AS Unit__apporved_at,
            Unit.status AS Unit__status,
            UnitAccount.id AS UnitAccount__id, UnitAccount.created_at AS UnitAccount__created_at, UnitAccount.updated_at AS UnitAccount__updated_at,
			UnitAccount.deleted_at AS UnitAccount__deleted_at, UnitAccount.created_by_id AS UnitAccount__created_by_id,
			UnitAccount.updated_by_id AS UnitAccount__updated_by_id, UnitAccount.deleted_by_id AS UnitAccount__deleted_by_id,
			UnitAccount.unit_id AS UnitAccount__unit_id, UnitAccount.bank_branch AS UnitAccount__bank_branch,
			UnitAccount.bank_type AS UnitAccount__bank_type, UnitAccount.account_name AS UnitAccount__account_name,
			UnitAccount.account_number AS UnitAccount__account_number
`
