### Get all products
GET http://localhost:3000/api/products
X-API-Key: RAHASIA
Accept: application/json

### Create new product
POST http://localhost:3000/api/products
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "Food"
}

### Get product by Id
GET http://localhost:3000/api/products/2
X-API-Key: RAHASIA
Accept: application/json

### Update product by id
PUT http://localhost:3000/api/products/2
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "Fashion"
}

### Delete product by id
DELETE http://localhost:3000/api/products/2
X-API-Key: RAHASIA
Accept: application/json
